import unittest
from pathlib import Path
import json
import numpy as np

# add the parent directory to sys.path to ensure imports work
import sys
ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from modeling.models.data_prep_network_size import load_cleaned_run_data, build_run_trajectory_from_clean

PARAMS = {
    'target_agent_fraction': 0.4,
    'constrain_messages': 150,
    'rollout_horizon_cap': 20,
}
REFERENCE_AGENT_SIZE = 30   


"""
    The log_correcter module reassigns timestamps to experiments and computes initial opinions for runs
        with many agents where the time manager may break down.

    This script tests the utilities in models/data_prep_network_size.py that load the cleaned data
        generated by log_correcter.py and verify that the recomputed initial opinions match the expected values.

"""

class TestLogLoading(unittest.TestCase):

    def test_load_build_pipeline_generic(self):

        # Given some reference logs, make sure that we get the expected 
        #  slice length will be approximately 8173 ms

        # Construct logs where 
        #   - We have two agents
        #   - The first agent has 3 messages, one in the first time slice, two in the third time slice, and none in the second or fourth time slices
        #   - The second agent has 2 messages, one in the third time slice and one in the fourth time slice
        # Test these logs for a variety of reference_agent_number values to ensure slicing is working

        # Build a temporary log directory
        temp_log_dir = Path(__file__).parent.resolve() / "temp_test_logs"
        # make sure the directory exists
        temp_log_dir.mkdir(parents=True, exist_ok=True)


        init_stance_map = {
            "agent_1": {"recomputed": 0.5, "sim_logged": 0.5},
            "agent_2": {"recomputed": -0.5, "sim_logged": -0.5},
        }
        # save the init_stance_map to a json file
        with open(temp_log_dir / "initial_stance_map.json", 'w') as f:
            json.dump(init_stance_map, f)

        messages_with_alignment = [
            {"sender_id": "agent_1", "published": {"stance_score": 0.4}, "time": {"t_ms": 0, "t_s": 0.0}},
            {"sender_id": "agent_1", "published": {"stance_score": 0.3}, "time": {"t_ms": 20000, "t_s": 20.0}},
            {"sender_id": "agent_1", "published": {"stance_score": 0.2}, "time": {"t_ms": 22000, "t_s": 22.0}},
            {"sender_id": "agent_2", "published": {"stance_score": -0.4}, "time": {"t_ms": 22000, "t_s": 22.0}},
            {"sender_id": "agent_2", "published": {"stance_score": -0.3}, "time": {"t_ms": 28000, "t_s": 28.0}},
        ]

        # save the messages_with_alignment to a jsonl file
        with open(temp_log_dir / "messages_with_alignment.jsonl", 'w') as f:
            for msg in messages_with_alignment:
                f.write(json.dumps(msg) + "\n")

        connection_graph = {
            "agent_1": ["agent_2"],
            "agent_2": ["agent_1"],
        }

        # save the connection_graph to a json file
        with open(temp_log_dir / "connection_graph.json", 'w') as f:
            json.dump(connection_graph, f)


        # now load the data using the load_cleaned_run_data function
        run_data = load_cleaned_run_data(temp_log_dir)
        traj_mask = build_run_trajectory_from_clean(
            data=run_data,
            global_agent_ids=["agent_1", "agent_2"],
            target_agent_fraction=PARAMS['target_agent_fraction'],
            constrain_messages=PARAMS['constrain_messages'],
            return_post_mask=True,
            reference_agent_number=REFERENCE_AGENT_SIZE
        )

        traj = traj_mask[0]
        mask = traj_mask[1]

        # check that both have the expect shape of 4 * 2
        self.assertEqual(traj.shape, (4, 2), "Trajectory shape does not match expected shape")
        self.assertEqual(mask.shape, (4, 2), "Mask shape does not match expected shape")

        ref_mask = np.array([[True, False], [False, False], [True, True], [False, True]])
        np.testing.assert_array_equal(mask, ref_mask, "Mask does not match expected values")

        ref_traj = np.array([[0.4, -0.5], [0.4, -0.5], [0.2, -0.4], [0.2, -0.3]])
        np.testing.assert_array_equal(traj, ref_traj, "Trajectory does not match expected values")


        # repeat, with a different number of reference agents to check
        traj_mask = build_run_trajectory_from_clean(
            data=run_data,
            global_agent_ids=["agent_1", "agent_2"],
            target_agent_fraction=PARAMS['target_agent_fraction'],
            constrain_messages=PARAMS['constrain_messages'],
            return_post_mask=True,
            reference_agent_number=120) # in this case, everything should happen in one time slice
        
        traj = traj_mask[0]
        mask = traj_mask[1]

        # check that both have the expect shape of 1 * 2
        self.assertEqual(traj.shape, (1, 2), "Trajectory shape does not match expected shape for reference_agent_number=120")
        self.assertEqual(mask.shape, (1, 2), "Mask shape does not match expected shape for reference_agent_number=120")

        ref_mask = np.array([[True, True]])
        np.testing.assert_array_equal(mask, ref_mask, "Mask does not match expected values for reference_agent_number=120")

        ref_traj = np.array([[0.2, -0.3]])
        np.testing.assert_array_equal(traj, ref_traj, "Trajectory does not match expected values for reference_agent_number=120")

        traj_mask = build_run_trajectory_from_clean(
            data=run_data,
            global_agent_ids=["agent_1", "agent_2"],
            target_agent_fraction=PARAMS['target_agent_fraction'],
            constrain_messages=PARAMS['constrain_messages'],
            return_post_mask=True,
            reference_agent_number=4)

        traj = traj_mask[0]
        mask = traj_mask[1]

        ref_mask = np.full((26, 2), False)
        ref_mask[0, 0] = True
        ref_mask[18,0] = True
        ref_mask[20,0] = True
        ref_mask[20,1] = True
        ref_mask[25,1] = True
        np.testing.assert_array_equal(mask, ref_mask, "Mask does not match expected values for reference_agent_number=4")

        ref_traj = np.full((26, 2), np.nan)

        for t in range(18):
            ref_traj[t, 0] = 0.4
            ref_traj[t, 1] = -0.5

        for t in range(18, 20):
            ref_traj[t, 0] = 0.3
            ref_traj[t, 1] = -0.5

        for t in range(20, 25):
            ref_traj[t, 0] = 0.2
            ref_traj[t, 1] = -0.4

        ref_traj[25, 0] = 0.2
        ref_traj[25, 1] = -0.3

        np.testing.assert_array_equal(traj, ref_traj, "Trajectory does not match expected values for reference_agent_number=4")

    def test_load_build_pipeline_init_timing(self):

        temp_log_dir = Path(__file__).parent.resolve() / "temp_test_logs"
        temp_log_dir.mkdir(parents=True, exist_ok=True)


        init_stance_map = {
            "agent_1": {"recomputed": 0.6, "sim_logged": 0.6},
            "agent_2": {"recomputed": -0.6, "sim_logged": -0.6},
        }
        # save the init_stance_map to a json file
        with open(temp_log_dir / "initial_stance_map.json", 'w') as f:
            json.dump(init_stance_map, f)

        messages_with_alignment = [
            {"sender_id": "agent_1", "published": {"stance_score": -0.4}, "time": {"t_ms": 4000, "t_s": 4.0}},
            {"sender_id": "agent_1", "published": {"stance_score": -0.2}, "time": {"t_ms": 20000, "t_s": 20.0}},
            {"sender_id": "agent_1", "published": {"stance_score": -0.1}, "time": {"t_ms": 22000, "t_s": 22.0}},
            {"sender_id": "agent_2", "published": {"stance_score": 0.4}, "time": {"t_ms": 22000, "t_s": 22.0}},
            {"sender_id": "agent_2", "published": {"stance_score": 0.2}, "time": {"t_ms": 28000, "t_s": 28.0}},
        ]

        # save the messages_with_alignment to a jsonl file
        with open(temp_log_dir / "messages_with_alignment.jsonl", 'w') as f:
            for msg in messages_with_alignment:
                f.write(json.dumps(msg) + "\n")

        connection_graph = {
            "agent_1": ["agent_2"],
            "agent_2": ["agent_1"],
        }

        # save the connection_graph to a json file
        with open(temp_log_dir / "connection_graph.json", 'w') as f:
            json.dump(connection_graph, f)

        run_data = load_cleaned_run_data(temp_log_dir)
        traj_mask = build_run_trajectory_from_clean(
            data=run_data,
            global_agent_ids=["agent_1", "agent_2"],
            target_agent_fraction=PARAMS['target_agent_fraction'],
            constrain_messages=PARAMS['constrain_messages'],
            return_post_mask=True,
            reference_agent_number=REFERENCE_AGENT_SIZE
        )

        traj = traj_mask[0]
        mask = traj_mask[1]

        # check that both have the expect shape of 3 * 2
        self.assertEqual(traj.shape, (3, 2), "Trajectory shape does not match expected shape")
        self.assertEqual(mask.shape, (3, 2), "Mask shape does not match expected shape")

        ref_mask = np.array([[True, False], [True, False], [True, True]])
        np.testing.assert_array_equal(mask, ref_mask, "Mask does not match expected values")

        ref_traj = np.array([[ -0.4, -0.6], [-0.2, -0.6], [-0.1, 0.2]])
        np.testing.assert_array_equal(traj, ref_traj, "Trajectory does not match expected values")

    def test_load_build_pipeline_dead_agent(self):

        # test a case with 3 agents where agent 2 sends no messages

        temp_log_dir = Path(__file__).parent.resolve() / "temp_test_logs"
        temp_log_dir.mkdir(parents=True, exist_ok=True)

        init_stance_map = {
            "agent_1": {"recomputed": 0.5, "sim_logged": 0.5},
            "agent_2": {"recomputed": -0.2, "sim_logged": -0.2},
            "agent_3": {"recomputed": -0.5, "sim_logged": -0.5},
        }

        # save the init_stance_map to a json file
        with open(temp_log_dir / "initial_stance_map.json", 'w') as f:
            json.dump(init_stance_map, f)

        messages_with_alignment = [
            {"sender_id": "agent_1", "published": {"stance_score": 0.4}, "time": {"t_ms": 6000, "t_s": 6.0}},
            {"sender_id": "agent_1", "published": {"stance_score": 0.3}, "time": {"t_ms": 20000, "t_s": 20.0}},
            {"sender_id": "agent_1", "published": {"stance_score": 0.2}, "time": {"t_ms": 22000, "t_s": 22.0}},
            {"sender_id": "agent_1", "published": {"stance_score": 0.1}, "time": {"t_ms": 24000, "t_s": 24.0}},
            {"sender_id": "agent_1", "published": {"stance_score": 0.0}, "time": {"t_ms": 26000, "t_s": 26.0}},
            {"sender_id": "agent_1", "published": {"stance_score": -0.1}, "time": {"t_ms": 28000, "t_s": 28.0}},

            {"sender_id": "agent_3", "published": {"stance_score": -0.4}, "time": {"t_ms": 22000, "t_s": 22.0}},
            {"sender_id": "agent_3", "published": {"stance_score": -0.2}, "time": {"t_ms": 24000, "t_s": 24.0}},
            {"sender_id": "agent_3", "published": {"stance_score": -0.3}, "time": {"t_ms": 28000, "t_s": 28.0}},
            {"sender_id": "agent_3", "published": {"stance_score": -0.2}, "time": {"t_ms": 32000, "t_s": 32.0}},
        ]

        # save the messages_with_alignment to a jsonl file
        with open(temp_log_dir / "messages_with_alignment.jsonl", 'w') as f:
            for msg in messages_with_alignment:
                f.write(json.dumps(msg) + "\n")

        connection_graph = {
            "agent_1": ["agent_2"],
            "agent_2": ["agent_3"],
            "agent_3": ["agent_1"],
        }

        # save the connection_graph to a json file
        with open(temp_log_dir / "connection_graph.json", 'w') as f:
            json.dump(connection_graph, f)

        # now load the data using the load_cleaned_run_data function
        run_data = load_cleaned_run_data(temp_log_dir)
        traj_mask = build_run_trajectory_from_clean(
            data=run_data,
            global_agent_ids=["agent_1", "agent_2", "agent_3"],
            target_agent_fraction=PARAMS['target_agent_fraction'],
            constrain_messages=PARAMS['constrain_messages'],
            return_post_mask=True,
            reference_agent_number=REFERENCE_AGENT_SIZE
        )

        traj = traj_mask[0]
        mask = traj_mask[1]

        ref_mask = np.array([
            [True, False, False],
            [True, False, True],
            [True, False, True],
            [False, False, True],
        ])
        np.testing.assert_array_equal(mask, ref_mask, "Mask does not match expected values for dead agent case")

        ref_traj = np.array([
            [0.4, -0.2, -0.5],
            [0.2, -0.2, -0.4],
            [-0.1, -0.2, -0.3],
            [-0.1, -0.2, -0.2],
        ])
        np.testing.assert_array_equal(traj, ref_traj, "Trajectory does not match expected values for dead agent case")




if __name__ == '__main__':
    unittest.main()